apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: default
  labels:
        app: mywebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebapp
      tier: frontend
  template:
    metadata:
      labels:
        app: mywebapp
        tier: frontend
    spec: # Pod Spec
      containers:
      - name: mycontainer
        image: devopstech24/java-spring-app-ci-pipeline:1.0.0-72
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: myconfigmapv1.0
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"  # 50 milli cores (1/20 CPU)
          limits:
            memory: "128Mi"  # 128 mebibytes
            cpu: "100m"
          