apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  namespace: default
  labels:
    app: myapp 
spec:
  selector:
    app: myapp
    tier: frontend
  ports:
  - port: 80
    protocol: TCP
    name: springboot
    targetPort: 8080
  type: NodePort